#!/usr/bin/env python
# Get highest text numbers. Deprecated. Use komserverstats instead.
# $Id: komlasttext,v 1.3 2003/09/02 18:20:13 kent Exp $
# (C) 2002 Kent Engström. Released under GPL.

import kom
import komparam
import sys
import getopt

# Connect and log in

param = komparam.Parameters(sys.argv[1:])
(conn, error) = param.connect_and_login(kom.CachedConnection)
if conn is None:
    sys.stderr.write("%s: %s\n" % (sys.argv[0], error))
    sys.exit(1)

# Check for options

conference = None

options, arguments = getopt.getopt(param.get_arguments(),
                                   "",
                                   ["conference=",
                                    ])
for (opt, optarg) in options:
    if opt == "--conference":
        confs = conn.lookup_name(optarg, want_pers = 1, want_confs = 1)
        if len(confs) == 1:
            conference = confs[0][0]
        elif len(confs) > 1:
            sys.stderr.write("%s is not a unique name\n"% optarg)
            sys.exit(1)
        else:
            sys.stderr.write("%s not found\n" % optarg)
            sys.exit(1)

# Get number of last text

if conference:
    last_text = conn.uconferences[conference].highest_local_no
else:
    last_text = kom.ReqFindPreviousTextNo(conn, sys.maxint).response()

print last_text
