#!/usr/bin/env python
# LysKOM Protocol A version 10 client interface for Python
# $Id: komlasttext,v 1.1 2002/01/13 20:27:28 kent Exp $
# (C) 1999 Kent Engström. Released under GPL.

import kom
import komparam
import sys

# Connect and log in

param = komparam.Parameters(sys.argv[1:])
(conn, error) = param.connect_and_login(kom.CachedConnection)
if conn is None:
    sys.stderr.write("%s: %s\n" % (sys.argv[0], error))
    sys.exit(1)

# Get number of last text

last_text = kom.ReqFindPreviousTextNo(conn, sys.maxint).response()
print last_text
